#!/bin/bash
     HOME=/usr/local/polaric-aprsd
CLASSPATH=$HOME/jcoord.jar:$HOME/aprs.jar:/usr/share/java/RXTXcomm.jar:/usr/share/java/scala-library.jar
SERIALPORTS=-Dgnu.io.rxtx.SerialPorts=/dev/TNC:/dev/ttyS0:/dev/ttyS1:/dev/ttyUSB0:/dev/ttyUSB1:/dev/ttyACM0:/dev/ttyACM1
    FLAGS=-Djava.net.preferIPv4Stack=true
  LOGFILE=$HOME/logs/aprsd.log
  INIFILE=$HOME/server.ini
  PIDFILE=$HOME/daemon.pid
     JAVA=java
         
###################################################
# We dont need to change anything below this line
###################################################
 
case "$1" in 
   start) 
         if start-stop-daemon --test --start --pidfile "$PIDFILE" --user root \
                 --startas "$JAVA" >/dev/null; then
             cd $HOME;\
              $JAVA -Xverify:none -server $SERIALPORTS $FLAGS -cp $CLASSPATH \
              aprs.Main $INIFILE >> $LOGFILE  2>&1 &
             echo $! > $PIDFILE
             echo ""
             sleep 4;
             
             # Mapserver specific things 
             rm -R /tmp/wms >& /dev/null
             rm -R /tmp/wms_raster >& /dev/null
             mkdir /tmp/wms
             mkdir /tmp/wms_raster
             chown www-data.www-data /tmp/wms
             chown www-data.www-data /tmp/wms
             
             # Start webserver 
             apache2ctl restart 
             beep -f 800 -n -f 1100 -n -f 1500
	 else
             echo "(already running)"
         fi
         ;;
   
   stop)
         echo -n "Stopping aprs daemon "
         if start-stop-daemon --test --start --pidfile "$PIDFILE" --user root \
                 --startas "$JAVA" >/dev/null; then   
            echo "(not running)"
         else
            echo "(killing `cat $PIDFILE`)"
            kill `cat $PIDFILE`  
            sleep 1
            rm $PIDFILE
         fi   
         ;;
	 
   reload)
         echo "Reload is not implemented!" >&2
         exit 3
         ;;
	 
   restart|force-reload)
	 $0 stop
	 sleep 2 
	 $0 start
	 ;;  
  
   *)
      echo "Usage: daemon start|stop"
      exit 2
      ;;
   
esac
exit 0
