
.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH POLARIC-IMPORTCERT 1 "April, 2023"
.SH NAME
polaric-importcert \- Import certificate for use in HTTPS backend

.SH SYNOPSIS
.B polaric-importcert
.RI " certificate private-key"
.br

.SH DESCRIPTION
polaric-passwd has a web-server backend. This can be run in HTTPS mode, but then it need 
a certificate. This script converts and imports an existing certificate into the Java keystore
so that it can be used by aprsd. The certificate and the private key should be in PEM format and
the private key should not be password protected.
.PP
This program and manual page was written by LA7ECA, Øyvind hanssen <ohanssen@acm.org>.
