.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH POLARIC-PASSWD 1 "November 06, 2019"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
polaric-passwd \- Set or change password of a user
.SH SYNOPSIS
.B polaric-passwd
.RI " username"
.br

.SH DESCRIPTION
polaric-passwd is an utility for changing passwords used to log in to 
Polaric Server. It is a simple wrapper for 'htpasswd' provided by the Apache
web server software. Please note that you have to manually add user to 
permissions list in /etc/polaric-aprsd/server.ini to grant SAR or admin 
access to the user. I hope to automate this in later versions.
.PP
This program and manual page was written by LA7ECA, Øyvind hanssen <ohanssen@acm.org>.
