#!/bin/bash
set -e
INIFILE=/etc/polaric-aprsd/server.ini


case "$1" in

    configure|reconfigure)
        if [ "$1" == "configure" ] ; then
           if ! id polaric > /dev/null 2>&1 ; then
               adduser --quiet --system --home /var/lib/polaric --no-create-home \
                   --group --disabled-password --shell /bin/false \
                   polaric
               usermod -G dialout polaric
           fi
           chown root:polaric /etc/polaric-aprsd/passwd
           chown root:polaric /etc/polaric-aprsd/keys
           chown root:polaric /etc/polaric-aprsd/keys/*
           chmod 640 /etc/polaric-aprsd/passwd
           chmod 750 /etc/polaric-aprsd/keys
           chmod 640 /etc/polaric-aprsd/keys/*
        
           chown polaric:adm /var/log/polaric
           chown polaric:adm /var/lib/polaric
           chmod 755 /var/log/polaric
           chmod 755 /var/lib/polaric
        fi  
        if [ -e "/etc/polaric-webapp/users" ] ; then
           echo
           echo "Found password file in polaric-webapp directory"
           echo "Making a copy in /etc/polaric-aprsd/passwd.webapp.old"
           cp /etc/polaric-webapp/users /etc/polaric-aprsd/passwd.webapp.old
        fi
        if [[ ! -e "/var/lib/polaric/users.dat" ]] ; then 
           echo "admin,null,false,true,Admin User,,DEFAULT,false" > /var/lib/polaric/users.dat
           chown polaric:polaric /var/lib/polaric/users.dat
           chmod 644 /var/lib/polaric/users.dat
        fi
        if [[ ! -e "/etc/polaric-aprsd/keys/keystore.jks" ]] ; then 
           polaric-importcert-snakeoil yes
        fi
        
        echo
        echo "******** Polaric-aprsd ********"
        echo "It is recommended to install the polaric-webapp2 package. It can also be used to configure"
        echo "the server. If this is the first time installataion, please set your CALLSIGN and restart!" 
        echo
        echo "Use the command 'polaric-setcall' to set the callsign"
        echo "Use the command 'polaric-restart' to restart server" 
        echo "Use command 'polaric-passwd' to change password or add new users"
        echo 
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
