#!/bin/bash
set -e


case "$1" in
    remove)
       # Nothing to do here
    ;;

    purge)
        if id polaric > /dev/null 2>&1 ; then
            deluser --quiet polaric || true
            delgroup --quiet --only-if-empty polaric || true
        fi
       
        if [ -d "/var/log/polaric" ]; then
            rm -R /var/log/polaric 
        fi
        if [ -e "/var/lib/polaric/config.xml" ]; then
            rm /var/lib/polaric/config.xml
        fi
        if [ -e "/var/lib/polaric/users.dat" ]; then
            rm /var/lib/polaric/users.dat
        fi
        if [ -e "/var/lib/polaric/stations.dat" ]; then
            rm /var/lib/polaric/stations.dat
        fi
        if [ -e "/var/lib/polaric/messages.dat" ]; then
            rm /var/lib/polaric/messages.dat
        fi
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Nothing to do here
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
