#!/bin/bash
set -e
INIFILE=/etc/polaric-aprsd/server.ini


case "$1" in

    configure|reconfigure)
        if [ "$1" == "configure" ] ; then
           if ! id polaric > /dev/null 2>&1 ; then
               adduser --quiet --system --home /var/lib/polaric --no-create-home \
                   --group --disabled-password --shell /bin/false \
                   polaric
               usermod -G dialout polaric
           fi
           chown -R polaric:adm /var/log/polaric /var/lib/polaric
           chmod 755 /var/log/polaric
           if [ -e "/var/lib/polaric/mapcache" ]; then
              chown -R www-data /var/lib/polaric/mapcache
           fi
        fi  
        
        db_get polaric-aprsd/callsign
        sed -e "s/default\.mycall = .*/default\.mycall = $RET/" $INIFILE > $INIFILE.tmp
        mv $INIFILE.tmp $INIFILE
        db_stop
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
