#!/bin/bash
set -e


case "$1" in
    remove)
       # Nothing to do here
    ;;

    purge)
       if id polaric > /dev/null 2>&1 ; then
           deluser --quiet polaric || true
           delgroup --quiet --only-if-empty polaric || true
       fi
       
       if [ -d "/var/log/polaric" ]; then
          rm -R /var/log/polaric 
       fi
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Nothing to do here
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
