#!/bin/bash

     JLIB=/usr/share/java
     PLIB=/usr/share/polaric/java
  PLUGINS=/usr/share/polaric/plugins

CLASSPATH="$JLIB/polaric-aprsd.jar:$PLIB/*:$PLUGINS/*"

SERIALPORTS="-Dgnu.io.rxtx.SerialPorts=/dev/TNC:/dev/ttyS0:/dev/ttyS1:/dev/ttyUSB0:/dev/ttyUSB1:/dev/ttyACM0:/dev/ttyACM1:/dev/rfcomm0:/dev/rfcomm1"

      FLAGS=-XX:+AggressiveHeap      
     LOGDIR=/var/log/polaric
    CONFDIR=/etc/polaric-aprsd
     WEBDIR=/usr/share/polaric
    DATADIR=/var/lib/polaric  
    LOGFILE=$LOGDIR/aprsd.log
    INIFILE=$CONFDIR/server.ini

       JAVA=/usr/bin/java
  JAVA_ARGS="$FLAGS $SERIALPORTS -Dconfdir=$CONFDIR -Ddatadir=$DATADIR -Dwebdir=$WEBDIR -Dlogdir=$LOGDIR" 
 
 
exec $JAVA $JAVA_ARGS -classpath $CLASSPATH no.polaric.aprsd.Main $INIFILE >> $LOGFILE 2>&1 
